### ISSUE TITLE
Bootstrap3 / less.php: glyphicon-halfling font files not found

### ISSUE THREAD

**Issue by telepath** [oyejorge/gpEasy-CMS#39]
The glyphicon-halfling font files are references as relative paths in the compiles css. Since the css lies in /data/_cache/ the font files are not found.
```css
@font-face {
    font-family: "Glyphicons Halflings";
    src: url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"), url("../fonts/glyphicons-halflings-regular.woff") format("woff"), url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"), url("../fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular") format("svg");
}
```
